name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: bundle install
#     - name: Build
#       run: bundle exec fastlane build
    - name: Run tests
      run: bundle exec fastlane test
